### PR TITLE
WiP: Rename disable variables, fixes #16

### LINKED ISSUE #16: [BUG]  org.jitsi.videobridge.xmpp.user.shard.MUC_NICKNAME is not unique
**Describe the bug**
The muc_nickname should be unique, see:  
  https://github.com/jitsi/jitsi-videobridge/blob/master/doc/muc.md

but it is a fixed value:

https://github.com/UdelaRInterior/ansible-role-jitsi-meet/blob/7ad0a1b910db66c5610c47dcd9801c617ab6b32b/templates/videobridge_sip-communicator.properties.j2#L14

### PR DESCRIPTION
**Pull request by tabacha**
Work in progress.

Please not
* that commits of PR #14 is included here
* I have not tested this changes

Feel free to test it yourself

### CODE REVIEW

File: templates/jitsi_meet_config.js.j2 [hunk 1]
```diff
@@ -86,9 +86,9 @@ var config = {
     // Audio
 
     // Disable measuring of audio levels.
-    // disableAudioLevels: false,
+    disableAudioLevels: {{ not ( jitsi_meet_show_audio_levels | bool ) | lower }},
```
Comment (santiagomr) [inline templates/jitsi_meet_config.js.j2:89]: I am testing these changes now. `jitsi_meet_show_audio_levels` variable were not defined in *defaults/main.yml* yet.

Comment (santiagomr) [reply templates/jitsi_meet_config.js.j2:89]: Better said, it wasn't renamed yet.

Comment (santiagomr) [reply templates/jitsi_meet_config.js.j2:89]: Here it should be `{{ (not jitsi_meet_show_audio_levels) | bool | lower }}`, otherwise the result is `False` instead of `false` and config.json can't be parsed correctly

File: templates/jitsi_meet_config.js.j2 [hunk 2]
```diff
@@ -170,7 +170,7 @@ var config = {
     desktopSharingChromeExtId: '{{ jitsi_meet_desktop_sharing_chrome_ext_id }}',
 
     // Whether desktop sharing should be disabled on Chrome.
-    desktopSharingChromeDisabled: {{ jitsi_meet_desktop_sharing_chrome_disabled }},
+    desktopSharingChromeDisabled: {{ not ( jitsi_meet_enable_desktop_sharing_chrome | bool ) | lower }},
```
Comment (santiagomr) [inline templates/jitsi_meet_config.js.j2:173]: Here it should be `{{ (not jitsi_meet_enable_desktop_sharing_chrome) | bool | lower }}`, otherwise the result is `False` instead of `false` and config.json can't be parsed correctly

File: templates/jitsi_meet_config.js.j2 [hunk 3]
```diff
@@ -180,7 +180,7 @@ var config = {
     desktopSharingChromeMinExtVersion: '0.1',
 
     // Whether desktop sharing should be disabled on Firefox.
-    desktopSharingFirefoxDisabled: {{ jitsi_meet_desktop_sharing_firefox_disabled }},
+    desktopSharingFirefoxDisabled: {{ not ( jitsi_meet_enable_desktop_sharing_firefox | bool ) | lower }},
```
Comment (santiagomr) [inline templates/jitsi_meet_config.js.j2:183]: Here it should be `{{ (not jitsi_meet_enable_desktop_sharing_firefox) | bool | lower }}`, otherwise the result is `False` instead of `false` and config.json can't be parsed correctly

File: templates/jitsi_meet_config.js.j2 [hunk 4]
```diff
@@ -338,7 +338,7 @@ var config = {
     // If third party requests are disabled, no other server will be contacted.
     // This means avatars will be locally generated and callstats integration
     // will not function.
-    disableThirdPartyRequests: {{ jitsi_meet_disable_third_party_requests | bool | lower  }},
+    disableThirdPartyRequests: {{ not (jitsi_meet_enable_third_party_requests | bool) | lower  }},
```
Comment (santiagomr) [inline templates/jitsi_meet_config.js.j2:341]: Here it should be `{{ (not jitsi_meet_enable_third_party_requests) | bool | lower  }}`, otherwise the result is `False` instead of `false` and config.json can't be parsed correctly

**Review by santiagomr — COMMENTED** [review]
Thanks for the improvements. It would only be necessary to adjust the details that I commented (I already applied those changes locally to prove it)

**Comment by santiagomr** [comment]
@tabacha, because you indicated this PR as WIP first I consult you, can I merge this to master right now?

I also noticed from the PR title that you were planning to fix bug #16 right here, but I don't see any changes regarding it. Did you advance something?

File: templates/jitsi_meet_config.js.j2 (hunk 1 above)
Comment (santiagomr) [reply templates/jitsi_meet_config.js.j2:89]: > Better said, it wasn't renamed yet.

Sorry, I just saw that you had renamed this variable

File: templates/jitsi_meet_config.js.j2 (hunk 4 above)
Comment (tabacha) [reply templates/jitsi_meet_config.js.j2:341]: Does this ``{{ (not jitsi_meet_enable_third_party_requests) | bool | lower }}`` work when the variable is a **string** like this: 
```
jitsi_meet_enable_third_party_requests: "false"
```
?

**Comment by tabacha** [comment]
> @tabacha, because you indicated this PR as WIP first I consult you, can I merge this to master right now?
> 
> I also noticed from the PR title that you were planning to fix bug #16 right here, but I don't see any changes regarding it. Did you advance something?

Feel free to merge and fix the thinks by yourself. I just have not enough time to test it. Please note my boolean question above.

File: templates/jitsi_meet_config.js.j2 (hunk 4 above)
Comment (santiagomr) [reply templates/jitsi_meet_config.js.j2:341]: Yes, that conditional works when the variable is of type string [ (string_type_var) return `true`, (**not** string_type_var) return `false` ]

Therefore, in the example you propose, it doesn't matter if `jitsi_meet_enable_third_party_requests: "false"` or `jitsi_meet_enable_third_party_requests: "true"` is indicated, the template will be generated without errors and always with the same result.

If your question came to the case for the backward compatibility for those who used the role previously, all the conditionals involved use variables that were renamed so they would not have defined values in their own projects.

In fact, all these changes will imply releasing a new major version of the role (v4.0.0)
